### ISSUE TITLE
Sonarr Integration

### ISSUE THREAD

**Issue by SonuMucesh** [SonuMucesh/NHK-Live-Stream-Recorder#5]
To enhance the script and simplify the process of archiving shows while avoiding duplicates, we can incorporate Sonarr integration.

 By using Sonarr we can check if the episode has been already download and therefore avoid duplicates. Additaonally, it allows us to keep the names for the videos uniform to work with Plex/Jellyfin.

**Comment by UpperCenter** [comment]
I'm on commit ab9a45a4d0a26d211edc2a21d409f035de18fce9 and there is a startup error. Using Unraid:
```python
LOCAL_TIMEZONE: Europe/London
RECORDING_PATH: /app/recordings
FFMPEG_LOG_PATH: /app/logs/ffmpeg.log
SERIES_IDS: ['2032', '4023', '4001', '2024']
EPG_URL: https://nwapi.nhk.jp/nhkworld/epg/v7b/world/now.json
LIVESTREAM_URL: https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8
SONARR_INTEGRATION: True
SONARR_URL: https://sonarr.example.uk
SONARR_API_KEY: REDACTED
SERIES_IDS_MAPPING: {'2032': '280400', '4023': '270769', '4001': '324849', '2024': '270609'}
Programs found from EPG
Programs list from EPG: 1 and current time is: 2023-10-14 16:54:16
Traceback (most recent call last):
File "/app/main.py", line 368, in <module>
main()
File "/app/main.py", line 300, in main
get_epg_now()
File "/app/main.py", line 76, in get_epg_now
sonarr(program)
File "/app/main.py", line 166, in sonarr
sonarr_date = datetime.strptime(episode['airDateUtc'], '%Y-%m-%dT%H:%M:%S%z').astimezone(pytz.UTC).date()
KeyError: 'airDateUtc'
```

**Comment by SonuMucesh** [comment]
> I'm on commit [ab9a45a](https://github.com/SonuMucesh/NHK-Live-Stream-Recorder/commit/ab9a45a4d0a26d211edc2a21d409f035de18fce9) and there is a startup error. Using Unraid:
> 
> ```python
> LOCAL_TIMEZONE: Europe/London
> RECORDING_PATH: /app/recordings
> FFMPEG_LOG_PATH: /app/logs/ffmpeg.log
> SERIES_IDS: ['2032', '4023', '4001', '2024']
> EPG_URL: https://nwapi.nhk.jp/nhkworld/epg/v7b/world/now.json
> LIVESTREAM_URL: https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index.m3u8
> SONARR_INTEGRATION: True
> SONARR_URL: https://sonarr.example.uk
> SONARR_API_KEY: REDACTED
> SERIES_IDS_MAPPING: {'2032': '280400', '4023': '270769', '4001': '324849', '2024': '270609'}
> Programs found from EPG
> Programs list from EPG: 1 and current time is: 2023-10-14 16:54:16
> Traceback (most recent call last):
> File "/app/main.py", line 368, in <module>
> main()
> File "/app/main.py", line 300, in main
> get_epg_now()
> File "/app/main.py", line 76, in get_epg_now
> sonarr(program)
> File "/app/main.py", line 166, in sonarr
> sonarr_date = datetime.strptime(episode['airDateUtc'], '%Y-%m-%dT%H:%M:%S%z').astimezone(pytz.UTC).date()
> KeyError: 'airDateUtc'
> ```

Hey sorry for the late reply, github didn't notify me. This issue is fixed in the latest commit. 
```
        sonarr_date = None
        try:
            sonarr_date = datetime.strptime(episode.get('airDateUtc', ''), '%Y-%m-%dT%H:%M:%S%z').astimezone(
                pytz.UTC).date()
        except Exception as e:
            pass
```
The issue was that sonarr episodes sometimes don't have that field. So I've made it added a try and catch to avoid that scenario. Let me know if you still get this issue with the latest commit, I'll try and dig in further 👍
